version: "3.4"
x-shared-postgres-environment: &x-shared-postgres-environment
  POSTGRES_DB: "${POSTGRES_DB}"
  POSTGRES_USER: "${POSTGRES_USER:-postgres}"
  # this variable should be set in a .env file or passed via the docker-compose cli
  POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"

x-shared-environment-defaults:
  - &RUBYOPT "${RUBYOPT}"
  - &APP_PORT "${APP_PORT:-3000}"
  - &EMAIL_HTTP_PORT "${EMAIL_HTTP_PORT:-1080}"
  - &EMAIL_SMTP_PORT "${EMAIL_SMTP_PORT:-1025}"
  - &WEBPACKER_DEV_SERVER_PORT "${WEBPACKER_DEV_SERVER_PORT:-3035}"

x-email-defaults: &x-email-defaults
  SMTP_HOST: "${EMAIL_HOST:-email}"
  SMTP_PORT: *EMAIL_SMTP_PORT
  SMTP_FROM_EMAIL: "${EMAIL_FROM_ADDR:-mutualaid@localhost}"
  SYSTEM_HOST_NAME: "${SYSTEM_HOST_NAME:-localhost}"

services:
  email:
    build:
      context: ../..
      dockerfile: ./docker/development/email/Dockerfile
    command: [ "mailcatcher", "--foreground", "--ip", "0.0.0.0" ]
    depends_on:
      - db
    ports:
      - target: 1080
        published: *EMAIL_HTTP_PORT
      - target: 1025
        published: *EMAIL_SMTP_PORT

  db:
    image: postgres:alpine
    environment:
      <<: *x-shared-postgres-environment
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - db:/var/lib/postgresql/data

  app:
    build:
      context: ../..
      dockerfile: ./docker/development/app/Dockerfile
      target: base
    command: [ "bundle", "exec", "rails", "server", "-b", "0.0.0.0" ]
    user: "${UID}"
    ports:
      - target: *APP_PORT
        published: *APP_PORT
    volumes:
      - ../..:/usr/src/app
      - gem_cache:/usr/local/bundle/
      - node_modules:/usr/src/app/node_modules
    depends_on:
      - db
    environment:
      <<: *x-shared-postgres-environment
      <<: *x-email-defaults
      RAILS_ENV: development
      POSTGRES_HOST: db
      WEBPACKER_DEV_SERVER_HOST: webpacker
      WEBPACKER_DEV_SERVER_PORT: *WEBPACKER_DEV_SERVER_PORT
      RUBYOPT: *RUBYOPT

  webpacker:
    build:
      context: ../..
      dockerfile: ./docker/development/app/Dockerfile
      target: base
    user: "${UID}"
    command: [ "./bin/webpack-dev-server" ]
    volumes:
      - ../..:/usr/src/app
      - gem_cache:/usr/local/bundle/
      - node_modules:/usr/src/app/node_modules
    ports:
      - target: *WEBPACKER_DEV_SERVER_PORT
        published: *WEBPACKER_DEV_SERVER_PORT
    environment:
      - NODE_ENV=development
      - RAILS_ENV=development
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0

volumes:
  db:
  gem_cache:
  node_modules:
