version: '3.4'

volumes:
  public:
  db:
  caddy_data:

services:
  db:
    image: postgres
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-ma}
      POSTGRES_DB: ${POSTGRES_DB:-mutualaid}
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "10"
  app:
    build:
      context: ../..
      dockerfile: ./docker/production/app/Dockerfile
    ports:
      - target: 3000
        published: 3000
    depends_on:
      - db
    environment:
      RAILS_ENV: production
      POSTGRES_HOST: db
      POSTGRES_USER: mat
      POSTGRES_DB: mutualaidtompkins
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      # You can set this by running
      # rake secret
      # The resulting key should be placed in a .env file
      # in this directory, or you can pass it to
      # docker-compose up --build -e SECRET_KEY_BASE=...
      # Otherwise the database setup step will fail
      SECRET_KEY_BASE: "${SECRET_KEY_BASE}"
      RAILS_LOG_TO_STDOUT: "true"
      RACK_TIMEOUT_SERVICE_TIMEOUT: 30
      SENDGRID_API_KEY: "${SENDGRID_API_KEY}"
      SMTP_ADDRESS: "${SMTP_ADDRESS}"
      SMTP_FROM_EMAIL: "${SMTP_FROM_EMAIL}"
      SMTP_PASSWORD: "${SMTP_PASSWORD}"
      SMTP_PORT: "${SMTP_PORT}"
      SMTP_USERNAME: "${SMTP_USERNAME}"
      SYSTEM_APP_NAME: "${SYSTEM_APP_NAME}"
      SYSTEM_EMAIL: "${SYSTEM_EMAIL}"
      SYSTEM_HOST_NAME: "${SYSTEM_HOST_NAME}"
      SYSTEM_PASSWORD: "${SYSTEM_PASSWORD}"
    volumes:
      - "public:/usr/src/app/public"
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "10"
  caddy:
    image: caddy
    volumes:
      - "/usr/src/config/Caddyfile:/etc/caddy/Caddyfile"
      - "caddy_data:/data"
      - "public:/config/public"
    ports:
      - 80:80
      - 443:443
    restart: always
    depends_on:
      - app
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "10"
