# As with config/credentials.yml, you never want to store sensitive information,
# like your database password, in your source code. If your source code is
# ever seen by anyone, they now have access to your database.
#
# Instead, provide the password as a unix environment variable when you boot
# the app. Read https://guides.rubyonrails.org/configuring.html#configuring-a-database
# for a full rundown on how to provide these environment variables in a
# production deployment.
#
# On Heroku and other platform providers, you may have a full connection URL
# available as an environment variable. For example:
#   DATABASE_URL="postgres://myuser:mypass@localhost/somedatabase"
#
# You can use this database configuration with:
#   production:
#     url: <%= ENV['DATABASE_URL'] %>
#
#
# Some less common options:
# -------------------------
# Schema search path. The server defaults to $user,public
#   schema_search_path: myapp,sharedapp,public
# Minimum log levels, in increasing order (defaults to warning):
# debug5, debug4, debug3, debug2, debug1, log, notice, warning, error, fatal, and panic
#   min_messages: notice

default: &default
  adapter:  postgresql
  encoding: unicode
  username: <%= ENV['POSTGRES_USER'].presence || nil %>
  password: <%= ENV['POSTGRES_PASSWORD'].presence || nil %>
  database: <%= ENV['POSTGRES_DB'].presence || nil %>
  # https://til.hashrocket.com/posts/6918d4e62b-use-postgresql-socket-in-databaseyml
  host:     <%= ENV['POSTGRES_HOST'].presence || '/var/run/postgres' %>
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool:     <%= ENV["RAILS_MAX_THREADS"].presence || 5 %>

development:
  <<: *default
  database: <%= ENV['POSTGRES_DB'].presence || 'mutualaid_development' %>

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default
  database: <%= ENV['POSTGRES_DB'].presence || 'mutualaid_test' %>

production:
  <<: *default
  database: <%= ENV['POSTGRES_DB'].presence || 'mutualaid_production' %>
  username: <%= ENV['POSTGRES_USER'].presence || 'mutualaid' %>
